### ISSUE TITLE
Comment replies in CP get locked up

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#12]
Noticed that when I make replies directly to a post within the control panel that the reply submission gets locked up and doesn't want to complete. It just keeps showing the "replying" message and graphic and nothing happens:

<img width="1392" alt="meerkat-comment-reply-bug" src="https://user-images.githubusercontent.com/274571/62967782-50069780-bdcf-11e9-9e9f-f8efbc9f6df3.png">

If I refresh the comments section then the reply appears so…something is askew! :P

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Thanks for the report; was able to reproduce. Will have this in 1.5.6 soon :)

**Comment by jeffwhitfield** [comment]
Any updates?  :D

**Comment by JohnathonKoster** [comment]
> Any updates? :D

Yep! There are some fundamental issues with the current version that are making this hard to resolve for good. This issue is going to be resolved with V3.x, which will be a free update for everyone. Essentially I need to refactor everything so that Meerkat things are done first, and everything else happens after-the-fact.

I am currently refactoring the plugin into "core" and "implementation". Core will supply the base functionality, and define the services required by the target system (Statamic, WordPress, etc.). This will also have `js-core` which will be a platform-independent client framework for JavaScript. Current PHP core dev is happening at https://github.com/Stillat/meerkat (this update will be content compatible - so no need to do anything after it drops)

**Comment by jeffwhitfield** [comment]
Cool man! Looking forward to it!  :)

This isn’t the worst bug really. I think I can add in a quick and dirty workaround for this one...at least until the new version is ready.  ;)

**Comment by JohnathonKoster** [comment]
@jeffwhitfield 

The issue with the UI locking up with replies/edits (and other actions) in the CP should be resolved as of v1.5.71; and can be downloaded from the Statamic Marketplace https://statamic.com/marketplace/addons/meerkat
